### ISSUE TITLE
[help wanted] ragdoll core install without linux install tutorial

### ISSUE THREAD

**Issue by TouseefX** [ragdolldynamics/ragdoll-blender#1]
I am trying to install Ragdoll Core but it is confusing me because they are just libery files and I don't know what to do with them. So I created this issuse, and there is no tutorial on installing it but how do I install it?

**Comment by davidlatwe** [comment]
Hey, @TouseefX  👋🏼 

Sorry for the lack of infomation, Linux installation guide only being mentioned in our forum at the moment. 

https://forums.ragdolldynamics.com/t/ragdoll-for-blender-early-access/1227/7


Ragdoll core installation on Linux is basically two steps:

1. Download the `RagdollCore*.zip`
2. Unpack it in your home directory, e.g. `/home/user-name`

For example, to install current lastest core:
```bash
cd ~/
wget https://content.ragdolldynamics.com/6fb6a202-bd24-4db0-8d03-40e8c306c20c/RagdollCore-linux-2024.03.07.zip
unzip RagdollCore-linux-2024.03.07.zip
```

If you prefer to place core libraries in elsewhere, env var `RAGDOLL_CORE_PATH` can be used. For example:

```bash
export RAGDOLL_CORE_PATH=/home/user-name/ragdolldynamics/core/2024.03.07/lib
```

We will soon be updating our website!

**Comment by TouseefX** [comment]
thank you it helped closed as done

**Comment by mottosso** [comment]
Download instructions for Ragdoll Core on Linux has been updated now, thanks for reporting this @TouseefX 

- https://learn.ragdolldynamics.com/sdk/download
